rush01: rush01.c exception.h rush_print.h
	gcc -o rush01.out rush01.c exception.h rush_print.h

rush02: rush02.c exception.h rush_print.h
	gcc -o rush02.out rush02.c exception.h rush_print.h

rush03: rush03.c exception.h rush_print.h
	gcc -o rush03.out rush03.c exception.h rush_print.h

rush04: rush04.c exception.h rush_print.h
	gcc -o rush04.out rush04.c exception.h rush_print.h

rush05: rush05.c exception.h rush_print.h
	gcc -o rush05.out rush05.c exception.h rush_print.h